import pytest
from pydantic import ValidationError

from app.decks.models import (
    BulletListBlock,
    DeckSpec,
    HeadingBlock,
    LayoutId,
    Panel,
    PanelListBlock,
    Slide,
    Theme,
)


def _valid_theme() -> Theme:
    return Theme(
        palette={"primary": "#3B82F6", "background": "#0D1B2E", "text": "#F2F2F2"},
        font_stack="Inter, system-ui, sans-serif",
    )


class TestDeckSpecValid:
    def test_accepts_minimal_valid_deck(self):
        spec = DeckSpec(
            theme=_valid_theme(),
            slides=[Slide(layout=LayoutId.COVER, title="Título")],
        )
        assert len(spec.slides) == 1
        assert spec.version == "1.0"

    def test_context_propagates_from_deckspec_to_nested_theme_validator(self):
        """
        Caminho real de produção: `structure.py::generate_deck_structure`
        chama `DeckSpec.model_validate(data, context=...)` no nível raiz —
        precisa propagar pro validador de `Theme`, aninhado dentro dele.
        """
        data = {
            "theme": {
                "palette": {"primary": "#1A2B3C", "background": "#F8FAFC", "text": "#111111"},
                "font_stack": "Inter",
            },
            "slides": [{"layout": "cover", "title": "X"}],
        }
        spec = DeckSpec.model_validate(data, context={"enforce_dark_background": False})
        assert spec.theme.palette["background"] == "#F8FAFC"

        with pytest.raises(ValidationError, match="claro demais"):
            DeckSpec.model_validate(data)  # sem context — guardrail continua ativo

    def test_slide_id_autogenerated_when_omitted(self):
        s1 = Slide(layout=LayoutId.COVER, title="A")
        s2 = Slide(layout=LayoutId.COVER, title="B")
        assert s1.id != s2.id


class TestLayoutIsClosed:
    def test_rejects_unknown_layout(self):
        with pytest.raises(ValidationError):
            Slide(layout="layout-inventado", title="X")

    def test_accepts_all_documented_layouts(self):
        for layout in LayoutId:
            Slide(layout=layout, title="X")  # não deve levantar

    def test_infographic_is_a_documented_layout(self):
        # adicionado em 2026-08-19 — trava explícita pra não "sumir" numa
        # futura reorganização do enum sem ninguém notar.
        assert LayoutId.INFOGRAPHIC in LayoutId
        assert LayoutId.INFOGRAPHIC.value == "infographic"


class TestBulletListBlock:
    def test_rejects_more_than_seven_items(self):
        with pytest.raises(ValidationError):
            BulletListBlock(items=[f"item {i}" for i in range(8)])

    def test_rejects_empty_list(self):
        with pytest.raises(ValidationError):
            BulletListBlock(items=[])

    def test_accepts_up_to_seven_items(self):
        BulletListBlock(items=[f"item {i}" for i in range(7)])  # não deve levantar


class TestThemePalette:
    @pytest.mark.parametrize("missing", ["primary", "background", "text"])
    def test_rejects_missing_required_role(self, missing):
        palette = {"primary": "#000", "background": "#0D1B2E", "text": "#111"}
        del palette[missing]
        with pytest.raises(ValidationError):
            Theme(palette=palette, font_stack="Inter")


class TestThemeBackgroundMustBeDark:
    """Guardrail 2026-08-21 — ver FEWSHOT_RULEBOOK.md: nenhum dos 59 exemplos
    de referência tem fundo principal claro, então isso é validado de
    verdade, não só pedido no prompt (fecha o bug de fundo quase-branco)."""

    @pytest.mark.parametrize("background", ["#FFFFFF", "#F5F5F5", "#EEEEEE", "#fff"])
    def test_rejects_light_backgrounds(self, background):
        with pytest.raises(ValidationError, match="claro demais"):
            Theme(
                palette={"primary": "#1A2B3C", "background": background, "text": "#111111"},
                font_stack="Inter",
            )

    @pytest.mark.parametrize(
        "background", ["#0D1B2E", "#0A0A0D", "#141F2E", "#1a0e0e", "#0f2418"]
    )
    def test_accepts_a_range_of_dark_hues(self, background):
        # a IA continua livre pra escolher QUALQUER matiz escuro — não é 1
        # cor fixa, é uma faixa de luminância (ver models.py).
        theme = Theme(
            palette={"primary": "#3B82F6", "background": background, "text": "#F2F2F2"},
            font_stack="Inter",
        )
        assert theme.palette["background"] == background

    def test_rejects_invalid_hex(self):
        with pytest.raises(ValidationError, match="não é um hex válido"):
            Theme(
                palette={"primary": "#1A2B3C", "background": "not-a-color", "text": "#111"},
                font_stack="Inter",
            )

    def test_accepts_light_background_when_guardrail_disabled_via_context(self):
        """
        Tarefa 1 (2026-08-21): checkbox desligado na tela = editorial pode
        ter paleta própria, mesmo clara — o contexto de validação
        (`enforce_dark_background=False`, propagado por `structure.py` via
        `DeckSpec.model_validate(data, context=...)`) desliga esse guardrail
        especificamente. Sem contexto (`model_validate` sem `context=`, ou
        construção direta `Theme(...)`), o guardrail continua ativo —
        retrocompatível com todo o resto do código.
        """
        theme = Theme.model_validate(
            {"palette": {"primary": "#1A2B3C", "background": "#F8FAFC", "text": "#111111"}, "font_stack": "Inter"},
            context={"enforce_dark_background": False},
        )
        assert theme.palette["background"] == "#F8FAFC"

    def test_still_rejects_light_background_when_context_explicitly_true(self):
        with pytest.raises(ValidationError, match="claro demais"):
            Theme.model_validate(
                {"palette": {"primary": "#1A2B3C", "background": "#FFFFFF", "text": "#111"}, "font_stack": "Inter"},
                context={"enforce_dark_background": True},
            )

    def test_rejects_light_background_when_no_context_passed_at_all(self):
        # comportamento padrão de sempre — nenhum código antigo que chama
        # Theme(...)/model_validate(...) sem `context=` deve mudar de
        # comportamento com essa mudança.
        with pytest.raises(ValidationError, match="claro demais"):
            Theme.model_validate(
                {"palette": {"primary": "#1A2B3C", "background": "#FFFFFF", "text": "#111"}, "font_stack": "Inter"}
            )


class TestThemeBackgroundAndPrimaryMustBeDistinguishable:
    """
    Achado real em produção (2026-08-21 (7)): a IA escolheu background=#081421
    e primary=#0A192F — quase idênticos (contraste 1.05:1). O CSS usa
    `primary` como cor de TEXTO nos slides de tela cheia (cover/section-break/
    closing invertem fundo↔primary) — ficou ilegível. Diferente do guardrail
    de fundo escuro (opinião de estilo, gated pelo checkbox), este é garantia
    de renderização legível — sempre ativo, com ou sem contexto.
    """

    def test_rejects_near_identical_background_and_primary(self):
        with pytest.raises(ValidationError, match="contraste baixo demais"):
            Theme(
                palette={"primary": "#0A192F", "background": "#081421", "text": "#F2F2F2"},
                font_stack="Inter",
            )

    def test_accepts_sufficiently_distinct_colors(self):
        theme = Theme(
            palette={"primary": "#3B82F6", "background": "#0D1B2E", "text": "#F2F2F2"},
            font_stack="Inter",
        )
        assert theme.palette["primary"] == "#3B82F6"

    def test_stays_active_even_when_dark_background_guardrail_is_disabled(self):
        """Não é opinião de estilo — não é desligado pelo checkbox (diferente de background_must_be_dark)."""
        with pytest.raises(ValidationError, match="contraste baixo demais"):
            Theme.model_validate(
                {
                    "palette": {"primary": "#0A192F", "background": "#081421", "text": "#F2F2F2"},
                    "font_stack": "Inter",
                },
                context={"enforce_dark_background": False},
            )

    def test_does_not_duplicate_error_when_hex_already_invalid(self):
        # background_must_be_dark já pega hex inválido antes — não deve chegar aqui
        with pytest.raises(ValidationError, match="não é um hex válido"):
            Theme(
                palette={"primary": "#0A192F", "background": "not-a-color", "text": "#111"},
                font_stack="Inter",
            )


class TestPanelListBlock:
    def test_rejects_fewer_than_two_panels(self):
        with pytest.raises(ValidationError):
            PanelListBlock(panels=[Panel(heading="Só um", text="x")])

    def test_rejects_more_than_four_panels(self):
        with pytest.raises(ValidationError):
            PanelListBlock(panels=[Panel(heading=f"H{i}", text="x") for i in range(5)])

    def test_accepts_two_to_four_panels(self):
        for n in (2, 3, 4):
            PanelListBlock(panels=[Panel(heading=f"H{i}", text="x") for i in range(n)])  # não deve levantar


class TestSlideEyebrowAndCitation:
    def test_default_to_none(self):
        slide = Slide(layout=LayoutId.INFOGRAPHIC, title="X")
        assert slide.eyebrow is None
        assert slide.citation is None

    def test_accepts_eyebrow_and_citation(self):
        slide = Slide(
            layout=LayoutId.INFOGRAPHIC, title="X",
            eyebrow="Categoria | Subcategoria", citation="Fonte — Autor",
        )
        assert slide.eyebrow == "Categoria | Subcategoria"
        assert slide.citation == "Fonte — Autor"


class TestSlideIdUniqueness:
    def test_rejects_duplicate_slide_ids(self):
        with pytest.raises(ValidationError):
            DeckSpec(
                theme=_valid_theme(),
                slides=[
                    Slide(id="a", layout=LayoutId.COVER, title="X"),
                    Slide(id="a", layout=LayoutId.CLOSING, title="Y"),
                ],
            )

    def test_allows_distinct_slide_ids(self):
        spec = DeckSpec(
            theme=_valid_theme(),
            slides=[
                Slide(id="a", layout=LayoutId.COVER, title="X"),
                Slide(id="b", layout=LayoutId.CLOSING, title="Y"),
            ],
        )
        assert len(spec.slides) == 2


class TestCompositionPieces:
    """Peças de composição do layout `infographic` (2026-08-21) — vocabulário
    fechado extraído dos 59 exemplos, ver FEWSHOT_RULEBOOK.md. Todas
    opcionais/None por padrão (retrocompatibilidade)."""

    def test_all_default_to_none(self):
        slide = Slide(layout=LayoutId.INFOGRAPHIC, title="X")
        assert slide.illustration_position is None
        assert slide.eyebrow_style is None
        assert slide.panel_style is None
        assert slide.arrangement is None
        assert slide.citation_style is None

    @pytest.mark.parametrize("position", ["left", "right", "background", "none"])
    def test_accepts_documented_illustration_positions(self, position):
        slide = Slide(layout=LayoutId.INFOGRAPHIC, title="X", illustration_position=position)
        assert slide.illustration_position == position

    def test_rejects_undocumented_illustration_position(self):
        with pytest.raises(ValidationError):
            Slide(layout=LayoutId.INFOGRAPHIC, title="X", illustration_position="floating")

    @pytest.mark.parametrize("style", ["chamfered-left", "pill-left", "pill-center", "none"])
    def test_accepts_documented_eyebrow_styles(self, style):
        slide = Slide(layout=LayoutId.INFOGRAPHIC, title="X", eyebrow_style=style)
        assert slide.eyebrow_style == style

    @pytest.mark.parametrize("style", ["void-frame", "bordered-card", "borderless-icon"])
    def test_accepts_documented_panel_styles(self, style):
        slide = Slide(layout=LayoutId.INFOGRAPHIC, title="X", panel_style=style)
        assert slide.panel_style == style

    def test_rejects_undocumented_panel_style(self):
        with pytest.raises(ValidationError):
            Slide(layout=LayoutId.INFOGRAPHIC, title="X", panel_style="glass-morphism")

    @pytest.mark.parametrize(
        "arrangement", ["stacked", "row", "comparison-columns", "sequence-numbered", "sequence-lettered"]
    )
    def test_accepts_documented_arrangements(self, arrangement):
        slide = Slide(layout=LayoutId.INFOGRAPHIC, title="X", arrangement=arrangement)
        assert slide.arrangement == arrangement

    @pytest.mark.parametrize("style", ["bar-circuit-corners", "bordered-card", "split-two"])
    def test_accepts_documented_citation_styles(self, style):
        slide = Slide(layout=LayoutId.INFOGRAPHIC, title="X", citation_style=style)
        assert slide.citation_style == style
