import pytest
from pydantic import ValidationError

from app.decks.models import (
    BulletListBlock,
    DeckSpec,
    HeadingBlock,
    LayoutId,
    Slide,
    Theme,
)


def _valid_theme() -> Theme:
    return Theme(
        palette={"primary": "#1A2B3C", "background": "#FFFFFF", "text": "#111111"},
        font_stack="Inter, system-ui, sans-serif",
    )


class TestDeckSpecValid:
    def test_accepts_minimal_valid_deck(self):
        spec = DeckSpec(
            theme=_valid_theme(),
            slides=[Slide(layout=LayoutId.COVER, title="Título")],
        )
        assert len(spec.slides) == 1
        assert spec.version == "1.0"

    def test_slide_id_autogenerated_when_omitted(self):
        s1 = Slide(layout=LayoutId.COVER, title="A")
        s2 = Slide(layout=LayoutId.COVER, title="B")
        assert s1.id != s2.id


class TestLayoutIsClosed:
    def test_rejects_unknown_layout(self):
        with pytest.raises(ValidationError):
            Slide(layout="layout-inventado", title="X")

    def test_accepts_all_six_documented_layouts(self):
        for layout in LayoutId:
            Slide(layout=layout, title="X")  # não deve levantar


class TestBulletListBlock:
    def test_rejects_more_than_seven_items(self):
        with pytest.raises(ValidationError):
            BulletListBlock(items=[f"item {i}" for i in range(8)])

    def test_rejects_empty_list(self):
        with pytest.raises(ValidationError):
            BulletListBlock(items=[])

    def test_accepts_up_to_seven_items(self):
        BulletListBlock(items=[f"item {i}" for i in range(7)])  # não deve levantar


class TestThemePalette:
    @pytest.mark.parametrize("missing", ["primary", "background", "text"])
    def test_rejects_missing_required_role(self, missing):
        palette = {"primary": "#000", "background": "#fff", "text": "#111"}
        del palette[missing]
        with pytest.raises(ValidationError):
            Theme(palette=palette, font_stack="Inter")


class TestSlideIdUniqueness:
    def test_rejects_duplicate_slide_ids(self):
        with pytest.raises(ValidationError):
            DeckSpec(
                theme=_valid_theme(),
                slides=[
                    Slide(id="a", layout=LayoutId.COVER, title="X"),
                    Slide(id="a", layout=LayoutId.CLOSING, title="Y"),
                ],
            )

    def test_allows_distinct_slide_ids(self):
        spec = DeckSpec(
            theme=_valid_theme(),
            slides=[
                Slide(id="a", layout=LayoutId.COVER, title="X"),
                Slide(id="b", layout=LayoutId.CLOSING, title="Y"),
            ],
        )
        assert len(spec.slides) == 2
